MenuButton,Selectコンポーネントのmui仕様に修正及びWorkflows,muiTheme,useOpenの変更
ryogosteeny/agile-project-management-tool pull request #18
Opened 2022-03-18 04:56 UTC by ryogosteeny

# やったこと

- `Menu.tsx,Menu.stories.tsx`→`MenuButton.tsx,MenuButton.stories.tsx`にリネーム
命名がMenuだとmuiのコンポーネント名と被る為、変更しました。

- `MenuButton.tsx、Select.tsx`をmui仕様への修正

-  muiButtonの不要なスタイルの修正実施

- `MenuButton.tsx`のuiロジックを`useOpen.tsx`にカスタムフックとして切り出し実施

- `useOpen.test.tsx`の削除
uiの制御の保守性はテストコードを書くのではなく、storybookで動作確認して担保しようとなった為、削除しました。

- `agile-project-management-test.yml`のtestの実行ステップのコメントアウト実施
現状テストファイルがなく、ciが落ちてしまう為、暫定的にコメントアウトしています。
テストファイルを作成した時点で、解除します。

- `BaseButton.tsx,BaseButton.stories.tsx`の削除
今後 muiを使用していく為、使う箇所で随時呼び出して使用していこうと思い削除しました。

2022-03-28 15:57 UTC, ryo-wens requested changes

2022-03-28 15:57 UTC, ryo-wens commented on src/components/atoms/Select.tsx
> +      <InputLabel sx={{ fontSize: '1.4rem', color: 'text.primary', display: 'block', mb: 0.5 }}>{label}</InputLabel>
fontSizeの値も再利用することが多くなると思うので、themeに切り出しておくとよいかなと思いました。

2022-03-28 15:57 UTC, ryo-wens commented on src/components/atoms/MenuButton.tsx
> +        sx={{ width: '32px', height: '32px', p: 0, bgcolor: 'secondary.main', color: 'secondary.dark' }}
マジックナンバーは使わないようにしましょう。
他のコンポーネントでアイコンボタンを作成するときに使用することになると思うので、`32`は定数にしておいた方がよいと思います。

2022-03-29 11:33 UTC, ryogosteeny commented
3763194

- 10px＝1remを実現する為`CssBaseLine`と`htmlFontSize`での設定実施
- プロダクトの仕様でfontSizeを14pxを基準に1.4remに設定し残りの`body2,button`を設定実施
※ subtitleなど他のTypographyは、まだ未定の為、決まり次第随時追加していきます。
- アイコンのwidth、heightのマジックナンバーの定数化の為、スタイルの定数ファイル作成と切り出し実施

2022-03-31 14:28 UTC, toshi1127 commented on src/components/atoms/MenuButton.stories.tsx
> +      event: () => {},
storybookにactions的なのがあるので使えるなら使うと良いと思います！

2022-03-31 14:28 UTC, toshi1127 commented on src/components/atoms/MenuButton.tsx
> +          <MenuItem onClick={() => handleMenuItem(menuItem.event)} key={menuItem.label}>
これだと新しく関数作られちゃうので、インラインで描かない方がよいです

2022-03-31 14:35 UTC, toshi1127 commented on src/constants/styles.ts
> +export const ICON_WIDTH: number = 32 as const;
どこも32になる訳ではないですよね…？
直接してもいいような気もするし、少なくともサイズごとに定義したほうが良さそうかなと思いました

2022-04-03 08:53 UTC, ryogosteeny commented
3ae9dae

- `Menu.stories.tsx`のeventにactionメソッドに修正

- `styles.tsx`のアイコンの値の修正。
デザインの仕様を確認をしたところアイコンのサイズが三つ程に分けれた為、サイズ毎に定義して使用していきたいと思います。

- `MenuButton.tsx`の関数のインラインに関しては、後に修正する為、コメントでtodo追加実施

2022-04-03 09:11 UTC, toshi1127 commented on src/components/atoms/MenuButton.tsx
> +      <Button
https://mui.com/api/icon-button/
とか
buttonbase使うのが良い？

2022-04-03 10:34 UTC, ryogosteeny commented
7e43069

- `MenuButton.tsx`の`Button`→`ButtonBase`に修正実施
アイコンの仕様的にborderRadiusが50%と4pxの2パターンある為、
`IconButton`は50%のケースのアイコンで使用していき、
`ButtonBase`は4pxのケースで使用していきたいと思います。

- `muiTheme.tsx`の`Button`の設定スタイルを削除
上記の変更に伴い、`Button`でのstyleの上書きが必要無くなった為、削除します。

2022-04-03 11:50 UTC, toshi1127 approved these changes

2022-04-03 16:29 UTC, ryo-wens approved these changes

2022-04-03 16:35 UTC, merged